biprob:
  # Publica o estado das juntas-----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
  # Posição dos Controladores---------------------------------------
  j_front_hip_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_front_hip_l
    pid: {p: 50.0, i: 0.01, d: 5.0}
  j_sagittal_hip_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_sagittal_hip_l
    pid: {p: 50.0, i: 0.01, d: 5.0}
  j_knee_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_knee_l
    pid: {p: 50.0, i: 0.01, d: 5.0}
  j_sagittal_ankle_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_sagittal_ankle_l
    pid: {p: 50.0, i: 0.01, d: 5.0}
  j_front_ankle_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_front_ankle_l
    pid: {p: 50.0, i: 0.01, d: 5.0}
  j_front_hip_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_front_hip_r
    pid: {p: 50.0, i: 0.01, d: 5.0}
  j_sagittal_hip_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_sagittal_hip_r
    pid: {p: 50.0, i: 0.01, d: 5.0}
  j_knee_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_knee_r
    pid: {p: 50.0, i: 0.01, d: 5.0}
    #pid: {p: 60.0, i: 0.05, d: 10.0}
  j_sagittal_ankle_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_sagittal_ankle_r
    pid: {p: 50.0, i: 0.01, d: 5.0}
  j_front_ankle_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_front_ankle_r
    pid: {p: 50.0, i: 0.01, d: 5.0}